worker_processes 1;
pid /tmp/nginx_quartic.pid;
error_log /tmp/nginx_quartic_error.log;
events {
    worker_connections 128;
}
http {
    access_log /tmp/nginx_quartic_access.log;
    server {
        listen 10.0.0.1:4433 ssl;
        server_name localhost;
        ssl_protocols TLSv1.3;
        ssl_ecdh_curve X25519MLKEM768:x25519:secp256r1:secp384r1;
        ssl_certificate     /home/lab/quartic/certs/server.crt;
        ssl_certificate_key /home/lab/quartic/certs/server.key;
        location / {
            return 200 'OK';
            add_header Content-Type text/plain;
        }
    }
}
